# Generated by Django 4.2.7 on 2024-05-21 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_user_id_sick_list_delete_reception_and_more'),
        ('users', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.DateTimeField(blank=True, null=True)),
                ('reception_time', models.TimeField(blank=True, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_users', to=settings.AUTH_USER_MODEL)),
                ('id_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_services', to='main.service')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
            },
        ),
    ]
