# Generated by Django 4.2.7 on 2024-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reception_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
