# Generated by Django 4.2.7 on 2024-05-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_reception_date_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='id_client',
            new_name='id_user',
        ),
    ]
