# Generated by Django 4.2.7 on 2024-05-21 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_user_id_sick_list_delete_reception_and_more'),
        ('users', '0007_rename_id_client_appointment_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_services', to='main.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
