# Generated by Django 4.2.7 on 2024-05-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_appointment_id_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='id_user',
            new_name='user',
        ),
    ]
