# Generated by Django 4.2.7 on 2024-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_user_appointment_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('В_обр', 'В обработке'), ('Подтв', 'Подтверждена'), ('Отм', 'Отменена')], default='В_обр', max_length=12),
        ),
    ]
