# Generated by Django 4.2.7 on 2024-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('В обрaботке', 'В обработке'), ('Подтверждена', 'Подтверждена'), ('Отменена', 'Отменена')], default='В обрaботке', max_length=12),
        ),
    ]
