# Generated by Django 4.2.7 on 2024-05-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('В обрaботке', 'В обработке'), ('Подтвержден', 'Подтвержден'), ('Отменен', 'Отменен')], default='В обрaботке', max_length=12),
        ),
    ]
