# Generated by Django 5.0.3 on 2024-03-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('ENT', 'ЛОР'), ('Surgery', 'Хирургия'), ('Gynecology', 'Гинекология'), ('Allergology-immunology', 'Аллерго-иммунология'), ('Dentistry', 'Стоматология'), ('Ophthalmology', 'Офтальмология'), ('Infectious_disease_specialist', 'Инфекционист'), ('Gastroentorology', 'Гастроэнторология'), ('Ultrasound_diagnostics', 'УЗИ диагностика'), ('Cardiology', 'Кардиология'), ('Endocrinology', 'Эндокринология'), ('Physiotherapy', 'Физиотерапия'), ('Psychiatry', 'Психиатрия'), ('Geneticist', 'Генетик'), ('Dermatology', 'Дерматология'), ('Neurology', 'Неврология'), ('Endoscopy', 'Эндоскопия'), ('Traumalogy-ortopedics', 'Травматология-ортопедия')], default='ЛОР', max_length=55)),
                ('dateTimeService', models.DateTimeField(auto_now=True)),
                ('mail_Or_Number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('doctors', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=450)),
            ],
        ),
    ]
