# Generated by Django 5.0.3 on 2024-03-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='mail_Or_Number',
        ),
        migrations.RemoveField(
            model_name='services',
            name='doctors',
        ),
        migrations.AddField(
            model_name='appointments',
            name='mail',
            field=models.EmailField(default=5, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='number',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='Salary',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='mail',
            field=models.EmailField(default=5, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_expirience',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='doctor',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='main.doctors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='dateTimeService',
            field=models.DateTimeField(),
        ),
    ]
