# Generated by Django 5.0.3 on 2024-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_service_title_alter_user_patronymic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор'},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'verbose_name': 'Прием'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга'},
        ),
        migrations.AlterModelOptions(
            name='shedule',
            options={'verbose_name': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='sick_list',
            options={'verbose_name': 'Больничный лист'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='reception',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
