# Generated by Django 5.0.3 on 2024-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_doctor_options_alter_reception_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'verbose_name': 'Прием', 'verbose_name_plural': 'Приемы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='shedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='sick_list',
            options={'verbose_name': 'Больничный лист', 'verbose_name_plural': 'Больничные листы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
