# Generated by Django 5.0.3 on 2024-05-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_options_service_description_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Shedule_number',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='id_shedule',
        ),
        migrations.AddField(
            model_name='reception',
            name='reception_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reception',
            name='id_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_services', to='main.service'),
        ),
        migrations.AlterField(
            model_name='sick_list',
            name='complaints',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Shedule',
        ),
    ]
