# Generated by Django 5.0.3 on 2024-05-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_doctor_shedule_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Job_title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.AlterField(
            model_name='reception',
            name='id_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_services', to='main.service'),
        ),
    ]
