# Generated by Django 5.0.3 on 2024-05-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='field_of_medicine',
        ),
    ]
