# Generated by Django 4.2.7 on 2024-05-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_service_field_of_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
