# Generated by Django 4.2.7 on 2024-05-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиентs', 'verbose_name_plural': 'Клиентыs'},
        ),
    ]
