# Generated by Django 4.2.7 on 2024-05-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_sick_list',
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
        migrations.DeleteModel(
            name='Sick_list',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
